# Generated by Django 3.0.2 on 2020-02-02 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameModel(
            old_name='topics',
            new_name='topic',
        ),
    ]
